sonar.projectKey=toheeb-orelope_Amdari-Project02
sonar.organization=toheeb-orelope

# Add these for better analysis
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/build/**,**/*.test.*
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# For Terraform/K8s scanning
sonar.terraform.enabled=true
sonar.kubernetes.enabled=true