apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: auth-service
  template:
    metadata:
      labels:
        svc: auth-service
      annotations:
        trivy-operator.aquasecurity.github.io/ignore-ids: "KSV-0121,KSV-0118"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "auth-service"
        vault.hashicorp.com/agent-inject-secret-auth-service.env: "secureflow/data/auth-service"
        vault.hashicorp.com/agent-inject-template-auth-service.env: |
          {{- with secret "secureflow/data/auth-service" -}}
          export DB_USER="{{ .Data.data.DB_USER }}"
          export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
          {{- end }}
    spec:
      serviceAccountName: auth-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: auth-service
          image: secureflow/auth-service:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: secureflow-config
          env:
            - name: DB_HOST
              value: auth-db
            - name: DB_NAME
              value: authdb
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: secureflow
spec:
  selector:
    svc: auth-service
  ports:
    - port: 5001
      targetPort: 5001
