apiVersion: v1
kind: ConfigMap
metadata:
  name: secureflow-config
  namespace: secureflow
data:
  AUTH_SERVICE_URL: "http://auth-service:5001"
  TRANSACTION_SERVICE_URL: "http://transaction-service:5002"