apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secureflow

resources:
  - namespace.yaml
  - configmap.yaml
  - databases.yaml
  - auth-service.yaml
  - transaction-service.yaml
  - frontend.yaml
