apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-service
  template:
    metadata:
      labels:
        svc: transaction-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transaction-service"
        vault.hashicorp.com/agent-inject-secret-transaction-service.env: "secureflow/data/transaction-service"
        vault.hashicorp.com/agent-inject-template-transaction-service.env: |
          {{- with secret "secureflow/data/transaction-service" -}}
          export DB_USER="{{ .Data.data.DB_USER }}"
          export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          {{- end }}
    spec:
      serviceAccountName: transaction-service
      containers:
        - name: transaction-service
          image: secureflow/transaction-service:latest   # CK-06
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: secureflow-config
          env:
            - name: DB_HOST
              value: transaction-db
            - name: DB_NAME
              value: transactiondb
          securityContext:
            privileged: true                # CK-04
            allowPrivilegeEscalation: true  # CK-04
            runAsUser: 0                    # CK-02
          # CK-05 — no resources.
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: secureflow
spec:
  selector:
    svc: transaction-service
  ports:
    - port: 5002
      targetPort: 5002