apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: secureflow
spec:
  template:
    spec:
      containers:
        - name: redacted
          image: postgres:14
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-run
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: postgres-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: init-sql
          configMap:
            name: auth-db-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-db
  namespace: secureflow
spec:
  template:
    spec:
      containers:
        - name: redacted
          image: postgres:14
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-run
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: postgres-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: init-sql
          configMap:
            name: transaction-db-init
