apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: secureflow
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-service
  namespace: secureflow
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: secureflow
automountServiceAccountToken: false
