apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/part-of: secureflow-observability
data:
  falco.yaml: |
    rules_files:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/rules.d

    json_output: true
    json_include_output_property: true
    json_include_tags_property: true

    stdout_output:
      enabled: true

    stderr_output:
      enabled: true

    file_output:
      enabled: false

    syslog_output:
      enabled: false

    http_output:
      enabled: false

    priority: notice

    buffered_outputs: false

    syscall_event_drops:
      actions:
        - log
        - alert
      rate: 0.03333
      max_burst: 10
