apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - daemonset.yaml

configMapGenerator:
  - name: falco-secureflow-rules
    namespace: falco
    files:
      - secureflow_rules.yaml=falco-rules.yaml

generatorOptions:
  disableNameSuffixHash: true
