name: DevSecOps Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  security-events: write
  pull-requests: read


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World, Happy coding! 🚀"